---
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
    - when: never


stages:
  - build
  - test
  - deploy


.test_template:
  image: python:3.11.7-slim
  stage: test
  dependencies: []
  before_script:
    - echo "Installing requirements ..."
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - apt update
    - apt install curl jq -y
  script:
    - echo "Run your tests"


build:
  stage: build
  dependencies: []
  script:
    - echo "Building docker image into docker hub registry"


test_lint:
  extends: .test_template
  script:
    - pylint --fail-under=7.0 app/


unit_tests:
  extends: .test_template
  script:
    - echo "Running unittests ..."
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml


test_coverage:
  extends: .test_template
  script:
    - pytest --cov=app --cov-report=xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week


deploy_on_local:
  stage: deploy
  rules:
    - if: "$CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH"
  dependencies: []
  script:
    - echo "Deploy fastapi application on AWS, Gitllab, and GCS registry"


deploy_on_main:
  stage: deploy
  rules:
    - if: "$CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH"
  environment:
    name: production
  dependencies: []
  script:
    - echo "Deploy fastapi application from the $CI_COMMIT_REF_NAME brach. I hope everything will happen in its best way"
