---
name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app tests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -v --disable-warnings

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install curl command
        run: sudo apt install curl -y
      
      - name: Install Render CLI
        run: >
             URL=https://github.com
             PATH=render-oss/cli/releases/download/v2.1.5
             FILE=cli_2.1.5_linux_amd64.zip
             curl -L $URL/$PATH/$FILE -o render-cli.zip
      
      - name: Unzip and move Render CLI
        run: |
             unzip render.zip
             sudo mv cli_v2.1.5 /usr/local/bin/render
       
      - name: Trigger deploy with Render CLI
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          CI: true
        run: >
             render deploys create
             ${{ vars.RENDER_PROD_SERVICE_ID }} --output json --confirm
